# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["strikethrough","smart","with_toc_data"]
highlighter:         pygments

# Permalinks
permalink:        /posts/:title/

# Setup
title:            Rajasekar Elango's Blog
tagline:          ""
description:      'Reflections on programming, technology, books.'
url:              http://erajasekar.com
baseurl:          '/'
paginate:         3
excerpt_separator: "<br>"
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

author:
  name:           'Rajasekar Elango'
  url:            http://erajasekar.com

# Custom vars
version:          1.3.0

github:
  repo:           https://github.com/erajasekar/erajasekar.github.io

disqusShortName:     erajasekarblog
twitterAccountName:   erajasekar
